### ISSUE TITLE
Turning off Log messages

### ISSUE THREAD

**Issue by frios** [Yacubane/esp32-arduino-matter#43]
Any way to turn off the constant stream of log messages? I have used 

` esp_log_level_set("*", ESP_LOG_NONE);`

but that only gets me to:

`D (57850985) chip[DMG]: 

D (57850985) chip[DMG]: 

I (57850995) chip[EM]: 

D (57850995) chip[EM]: 

D (57850996) chip[EM]: 

D (57850997) chip[DMG]: 

D (57850997) chip[DMG]: 

D (57850998) chip[DMG]:`

I am trying to debug using some Serial.print statements and they just get lost in the constant serial output from the logging.

**Comment by Yacubane** [comment]
https://github.com/Yacubane/esp32-arduino-matter/issues/37 ;)
