### ISSUE TITLE
Is there a new release on the horizon?

### ISSUE THREAD

**Issue by weidingerc** [Yacubane/esp32-arduino-matter#45]

**Comment by Yacubane** [comment]
You asked, you got this ;) New version just landed!

**Comment by Robothaler** [comment]
Hi @Yacubane  I don't want to push but it would be cool if you could update Matter to v1.2.0.1. There are some improvements that might be helpful for my WindowCovering project. There is a new Mode Base Cluster where I hope to be able to create a switch for the calibration process of my roller shutter.
